### ISSUE TITLE
Validation support. date data type support

### ISSUE THREAD

**Issue by BlackRule** [eScienceCenter/dbWebGen#28]
The original issue is below but now I believe THERE must exist user-defined validation function!!! Such function should check field values and prevent form from submitting with error popup
Isn't it possible to implement drop down calendar and corresponding datatype/field type? Thank you very much for your great project I'd donate if I had money...

**Comment by BlackRule** [comment]
I'm currently using this project to make an assignment in university.. I would with some pain implement it myself and merge request here but hardly since I have no spare time. PS: When/if I'm done with the assignment I'll maybe post here Russian localisation (along with de and en it'll rest...)

**Comment by BlackRule** [comment]
Oh, ok let my date be  string Just tell me how do I define a validation function that won't let user fost the form until function returns true... I need to do some validation (call PHP isdate(value) and chck whether value is not later than today...))

**Comment by derntl** [comment]
Date picker is a good idea, not implemented yet. String input is fine however, because the DB accepts many different string formats as inputs formats for a date field (e.g. `'2018-05-01'` or `May 1, 2018`). 

About the form validation: this is also not implemented yet. I tried to keep application logic away from the engine. A constraint like this can easily be formulated in the DB, e.g. `date_of_issue date check (date_of_issue <= CURRENT_DATE);` -- if this check fails the DB will throw an error which will be displayed in the form when submitted.

**Comment by BlackRule** [comment]
Yes I thought about constraint but: Be message can't be translated So it's not user friendly at all... I'll have to change your code somehow (( because I need error messages in Russian.. Is it hard to implement?

**Comment by derntl** [comment]
I cannot tell if it will be hard. Submitted form data is handled in the `process_form` function in `inc/new_edit.php`

**Comment by derntl** [comment]
It is now possible to provide a custom form validation function. See commit 1c71f16e51e648c934d10af29ba24a96e841ac38

To see how it works look for `validation_func` instructions in `settings.template.php` and the example in the latest commit in the demo repository eScienceCenter/dbWebGen-demo@786035c50158bf462e54185dd7b4a8a000a6d48b
